spring security
BohdanZorii/book-web-store pull request #10
Opened 2024-07-18 09:56 UTC by BohdanZorii

2024-07-18 18:22 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution

2024-07-18 18:22 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/model/Role.java
> +        return "ROLE_" + role.name();
```suggestion
        return role.name();
```

2024-07-18 18:22 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/model/User.java
> +    @ManyToMany(fetch = FetchType.EAGER)
```suggestion
    @ManyToMany
```

2024-07-18 18:22 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/model/User.java
> +        return roles.stream()
```suggestion
        return roles;
```

2024-07-18 18:22 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/model/User.java
> +    public String getUsername() {
Where other methods of UserDetails?

2024-07-18 18:22 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/security/CustomUserDetailsService.java
> +@Transactional
```suggestion
```

2024-07-18 18:22 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/security/CustomUserDetailsService.java
> +        Hibernate.initialize(user.getRoles());
```suggestion
```

2024-07-18 18:22 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/security/CustomUserDetailsService.java
> +                new UsernameNotFoundException("Can't find user by email " + username));
```suggestion
                new EntityNotFoundException("Can't find user by email " + username));
```

2024-07-18 18:22 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/security/CustomUserDetailsService.java
> +        User user = userRepository.findByEmail(username).orElseThrow(() ->
```suggestion
        return userRepository.findByEmail(username).orElseThrow(() ->
```

2024-07-19 09:56 UTC, BohdanZorii commented on src/main/java/mate/zorii/bookstore/model/User.java
> +    public String getUsername() {
they're default

2024-07-20 11:30 UTC, Elena-Bruyako approved these changes
good jo

2024-07-20 11:35 UTC, merged