Shopping cart
BohdanZorii/book-web-store pull request #14
Opened 2024-07-21 09:03 UTC by BohdanZorii

2024-07-21 09:21 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution

2024-07-21 09:21 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/controller/BookController.java
> +    public BookDto findById(@PathVariable @Positive Long id) {
add `@Validated` under the controller

2024-07-21 09:21 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/controller/CategoryController.java
> +    public CategoryDto getCategoryById(@PathVariable @Positive Long id) {
same

2024-07-21 09:21 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/dto/shoppingcart/CartItemDto.java
> +        @Min(value = 1, message = "Quantity must be at least 1")
```suggestion
        @Positive(value = 1, message = "Quantity must be at least 1")
```

2024-07-21 09:21 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/dto/shoppingcart/CartItemUpdateDto.java
> +        @Min(value = 1, message = "Quantity must be at least 1")
```suggestion
        @Positive(value = 1, message = "Quantity must be at least 1")
```

2024-07-21 09:21 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/model/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-07-21 09:21 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/model/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-07-21 09:21 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/model/ShoppingCart.java
> +@Table(name = "shoppingCarts")
```suggestion
@Table(name = "shopping_carts")
```

2024-07-21 09:21 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/model/ShoppingCart.java
> +    @OneToOne(fetch = FetchType.EAGER)
```suggestion
    @MapsId
    @OneToOne(fetch = FetchType.LAZY)
```

you can use MapsId here

2024-07-21 09:21 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/repository/CartItemRepository.java
> +    Optional<CartItem> findCartItemByBook_IdAndShoppingCart(Long bookId, ShoppingCart shoppingCart);
It's better to use
```suggestion
    Optional<CartItem> findByIdAndShoppingCartId(Long cartItemId, Long shoppingCartId);
```

2024-07-21 09:21 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/repository/ShoppingCartRepository.java
> +    Optional<ShoppingCart> findShoppingCartByUser_Id(Long userId);
```suggestion
    @EntityGraph(attributePaths = {"cartItems", "cartItems.book"})
    ShoppingCart findByUserId(Long userId);
```

2024-07-21 09:21 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/service/ShoppingCartService.java
> +    CartItemDto addCartItem(CartItemDto cartItemDto, Long authenticatedUser);
```suggestion
    ShoppingCartResponseDto addCartItem(CartItemDto cartItemDto, Long authenticatedUser);
```

2024-07-21 09:21 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/service/ShoppingCartService.java
> +    CartItemDto updateCartItem(Long cartItemId, CartItemUpdateDto cartItemUpdateDto);
```suggestion
    ShoppingCartResponseDto updateCartItem(Long cartItemId, CartItemUpdateDto cartItemUpdateDto);
```

2024-07-21 09:21 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/service/impl/ShoppingCartServiceImpl.java
> +    @Override
Add `@Transactional` where is needed

2024-07-21 09:21 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/service/impl/ShoppingCartServiceImpl.java
> +        System.out.println("was here");
```suggestion
```

2024-07-21 09:21 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/service/impl/ShoppingCartServiceImpl.java
> +        cartItemRepository.deleteById(id);
```suggestion
        ShoppingCart shoppingCart = shoppingCartRepository.findByUserId(userId);
        CartItem cartItem = cartItemRepository.findByIdAndShoppingCartId(itemId, shoppingCart.getId())........
        cartItemRepository.deleteById(id);
```

2024-07-21 09:21 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/service/impl/ShoppingCartServiceImpl.java
> +    public void deleteCartItem(Long id) {
```suggestion
    public void deleteCartItem(Long id, Long userId) {
```

2024-07-21 09:21 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/service/impl/ShoppingCartServiceImpl.java
> +        return mapper.toCartItemDto(cartItemRepository.save(cartItem));
```suggestion
        ShoppingCart cart = shoppingCartRepository.findByUserId(userId);
        CartItem cartItem = cartItemRepository.findByIdAndShoppingCartId(cartItemId, cart.getId())
                .map(item -> {
                    item.setQuantity(itemDto.quantity());
                    return item;
                }).orElseThrow(() -> new EntityNotFoundException(
                        String.format("No cart item with id: %d for user: %d", cartItemId, userId)
                ));
        cartItemRepository.save(cartItem);
        return cartMapper.toDto(cart);
```

2024-07-21 09:21 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/service/impl/ShoppingCartServiceImpl.java
> +        ShoppingCart shoppingCart = getCartByUserId(userId);
```
Book book = bookRepository.findById
ShoppingCart cart = repository.findByUserId(userId);
cart.getCartItems().stream() .... 
```
if book exists - increase quantity
if no - add to cart
```
repository.save(cart);
return cartMapper.toDto(cart);
```

2024-07-21 09:21 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/service/impl/UserServiceImpl.java
> +
```suggestion
        userRepository.save(user);
        shoppingCartService.createShoppingCart(user);
```

Where in ShoppingCartServiceImpl

```
@Override
    public void createShoppingCart(User user) {
        ShoppingCart shoppingCart = new ShoppingCart();
        shoppingCart.setUser(user);
        repository.save(shoppingCart);
    }
```

2024-07-21 10:17 UTC, BohdanZorii commented on src/main/java/mate/zorii/bookstore/repository/CartItemRepository.java
> +    Optional<CartItem> findCartItemByBook_IdAndShoppingCart(Long bookId, ShoppingCart shoppingCart);
I don't get cartItemId from client when creating cartItem. Moreover, I don't see how this checks, if cartItem with the concrete book is already present in the shoppingCart

2024-07-22 14:26 UTC, Elena-Bruyako requested changes
one comment

2024-07-22 14:26 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/service/impl/ShoppingCartServiceImpl.java
> +        return findByUserId(userId);
Could we avoid calling DB ?

2024-07-23 09:18 UTC, Elena-Bruyako requested changes
Well done. Left some comments

2024-07-23 09:18 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/dto/shoppingcart/CartItemDto.java
> +        @NotNull(message = "Quantity cannot be null")
```suggestion
```
Didn't mention before, primitive type can't be null

2024-07-23 09:18 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/dto/shoppingcart/CartItemUpdateDto.java
> +        @NotNull(message = "Quantity cannot be null")
```suggestion
```

2024-07-23 09:18 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/model/ShoppingCart.java
> +    @OneToMany(mappedBy = "shoppingCart", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
```suggestion
    @OneToMany(mappedBy = "shoppingCart", cascade = CascadeType.ALL, orphanRemoval = true)
```

Lazy by default

2024-07-23 09:18 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/service/impl/ShoppingCartServiceImpl.java
> +        cartItemRepository.findByIdAndShoppingCart_Id(cartItemId, userId)
You are trying to find cart item by id and shopCart id, but provide cart item id and user id
```suggestion
        ShoppingCart shoppingCart = shoppingCartRepository.findByUserId(userId);
        CartItem cartItem = cartItemRepository.findByIdAndShoppingCartId(cartItemId, shoppingCart.getId())
```

2024-07-23 09:18 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/service/impl/ShoppingCartServiceImpl.java
> +    @Override
```suggestion
    @Override
    @Transactional
```

2024-07-23 09:18 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/service/impl/UserServiceImpl.java
>      @Override
```suggestion
    @Override
    @Transactional
```

2024-07-23 12:08 UTC, BohdanZorii commented on src/main/java/mate/zorii/bookstore/model/ShoppingCart.java
> +    @OneToMany(mappedBy = "shoppingCart", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
it was said that it's better to set it explicitly

2024-07-24 13:52 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/model/ShoppingCart.java
> +    @OneToMany(mappedBy = "shoppingCart", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
Not required. Some teams prefer to not use default values due to leave code readable

2024-07-24 13:57 UTC, Elena-Bruyako approved these changes
And we have done with this part eventually )) Congrats

2024-07-24 17:41 UTC, merged