Orders placing
BohdanZorii/book-web-store pull request #15
Opened 2024-07-23 14:51 UTC by BohdanZorii

2024-07-25 18:15 UTC, BohdanZorii commented
ongoing issue fix conversation in jv_chat_1

2024-07-26 08:39 UTC, Elena-Bruyako requested changes
See comments

2024-07-26 08:39 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/controller/OrderController.java
> +        return orders;
```suggestion
        return orderService.placeOrder(user.getId(), requestDto);
```

2024-07-26 08:39 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/controller/OrderController.java
> +    public List<OrderResponseDto> placeOrder(@RequestBody @Valid CreateOrderRequestDto requestDto,
```suggestion
    public OrderDto placeOrder(@RequestBody @Valid CreateOrderRequestDto requestDto,
```

2024-07-26 08:39 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/controller/OrderController.java
> +    public List<OrderResponseDto> updateOrderStatus(
```suggestion
    public UpdateOrderResponseDto updateOrderStatus(
```

2024-07-26 08:39 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/service/impl/OrderServiceImpl.java
> +        Order order = new Order();
```suggestion
        ShoppingCart cart = cartRepository.findByUserId(userId);
        if (cart.getCartItems().isEmpty()) {
            .....
        }
        Order order = orderMapper.cartToOrder(cart, orderDto.shippingAddress());
        cart.clearCart();
        return orderMapper.toOrderDto(orderRepository.save(order));
```

Where in OrderMapper class

```
@Mapping(target = "id", ignore = true)
@Mapping(target = "total", source = "cart.cartItems", qualifiedByName = "total")
@Mapping(target = "orderItems", source = "cart.cartItems")
Order cartToOrder(ShoppingCart cart, String shippingAddress);
```

and 

```
@Named("total")
    default BigDecimal getTotal(Set<CartItem> cartItems) {
        return cartItems.stream()
                .map(i -> i.getBook().getPrice().multiply(BigDecimal.valueOf(i.getQuantity())))
                .reduce(BigDecimal.ZERO, BigDecimal::add);
    }
```

and 
```
@AfterMapping
    default void updateOrder(@MappingTarget Order order) {
        order.getOrderItems().forEach(oi -> oi.setOrder(order));
    }
```

and in ShoppingCart class
```
public void clearCart() {
        cartItems.clear();
    }
```

2024-07-26 08:39 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/model/Order.java
> +    private Status status;
```suggestion
    private Status status = Status.PENDING;
```

2024-07-26 08:39 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/model/Order.java
> +    private LocalDateTime orderDate;
```suggestion
    private LocalDateTime orderDate = LocalDateTime.now();
```

2024-07-26 08:39 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/mapper/OrderMapper.java
> +    OrderItemResponseDto toOrderItemDto(OrderItem orderItem);
create OrderItemMapper for mapping logic with OrderItem

2024-07-26 08:39 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/service/impl/ShoppingCartServiceImpl.java
> +    public void addCartItem(CartItemDto cartItemDto, Long userId) {
revert please

2024-07-26 08:39 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/service/impl/ShoppingCartServiceImpl.java
> +        entityManager.clear();
what is it?

2024-07-26 08:39 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/service/impl/ShoppingCartServiceImpl.java
> +    public void clearCart(Long userId) {
remove

2024-07-26 08:39 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/service/impl/ShoppingCartServiceImpl.java
> +    public Set<CartItem> getCartItemsByUserId(Long userId) {
remove

2024-07-26 17:51 UTC, BohdanZorii commented
get 'cannot persist detached entity orderItem', when trying to place an order

2024-07-27 15:36 UTC, BohdanZorii commented
> get 'cannot persist detached entity orderItem', when trying to place an order

fixed by saving order to have id before setting orderItems

2024-07-27 17:40 UTC, sarakhmen approved these changes
lgtm!

2024-07-28 07:24 UTC, merged