docker
BohdanZorii/book-web-store pull request #16
Opened 2024-08-01 07:28 UTC by BohdanZorii

2024-08-02 13:22 UTC, okuzan requested changes
add .env to gitignore, remove it from repo with git rm --cached .env, create .env.template with actual values removed.

2024-08-02 17:59 UTC, BohdanZorii commented on docker-compose.yaml
> +      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
should I change it? I've found that it has to be 5005 for remote debugging purposes

2024-08-03 11:43 UTC, okuzan approved these changes

2024-08-03 11:43 UTC, okuzan commented on env.template
> +DEBUG_PORT=5005
```suggestion
MYSQL_DOCKER_PORT=

SPRING_LOCAL_PORT=<your_spring_local_port>
SPRING_DOCKER_PORT=
DEBUG_PORT=
```

2024-08-03 18:33 UTC, merged