Validation and global exception handler
BohdanZorii/book-web-store pull request #6
Opened 2024-06-30 09:42 UTC by BohdanZorii

2024-06-30 10:15 UTC, MentorMateAcademy requested changes

2024-06-30 10:15 UTC, MentorMateAcademy commented on src/main/java/mate/zorii/bookstore/dto/BookDto.java
> +    @Min(0)
```suggestion
    @Positive
```

2024-06-30 16:23 UTC, sarakhmen requested changes
let's improve your solution :)

2024-06-30 16:23 UTC, sarakhmen commented on src/main/java/mate/zorii/bookstore/exception/GlobalExceptionHandler.java
> +    }
let's put private methods after public ones

2024-06-30 16:23 UTC, sarakhmen commented on src/main/java/mate/zorii/bookstore/exception/GlobalExceptionHandler.java
> +
```suggestion
```

2024-06-30 16:23 UTC, sarakhmen commented on src/main/java/mate/zorii/bookstore/dto/CreateOrUpdateBookRequestDto.java
> +
```suggestion
```

2024-06-30 16:23 UTC, sarakhmen commented on src/main/java/mate/zorii/bookstore/dto/BookDto.java
> +
```suggestion
```

2024-06-30 16:23 UTC, sarakhmen commented on src/main/java/mate/zorii/bookstore/dto/CreateOrUpdateBookRequestDto.java
> +    @Min(0)
not fixed

2024-07-01 09:18 UTC, Elena-Bruyako requested changes
Let's improve your solution

2024-07-01 09:18 UTC, Elena-Bruyako commented on pom.xml
> +			<groupId>org.hibernate.validator</groupId>
Use spring-boot-starter-validation instead, which provides hibernate-validator also

2024-07-01 09:18 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(NullPointerException.class)
remove

2024-07-01 09:18 UTC, Elena-Bruyako commented on src/main/java/mate/zorii/bookstore/exception/GlobalExceptionHandler.java
> +        return new ResponseEntity<>("An unexpected error occurred",
It's better provide more information about the exception. 
When you got this message, you won't understand what exactly happened

2024-07-01 11:40 UTC, BohdanZorii commented
accidentally commited to a wrong branch at first

2024-07-01 11:44 UTC, MentorMateAcademy approved these changes

2024-07-01 11:44 UTC, MentorMateAcademy commented on src/main/java/mate/zorii/bookstore/dto/BookDto.java
> +
Not fixed

2024-07-02 06:29 UTC, merged